export const glassPresets = {
  nav: {
    overLight: true,
    cornerRadius: 100,
    displacementScale: 74,
    blurAmount: 0.18,
    saturation: 180,
    elasticity: 0.24,
    padding: '12px 24px',
  },
  heroCard: {
    overLight: true,
    cornerRadius: 34,
    displacementScale: 112,
    blurAmount: 0.22,
    saturation: 190,
    elasticity: 0.18,
    padding: '42px',
  },
  card: {
    overLight: true,
    cornerRadius: 30,
    displacementScale: 96,
    blurAmount: 0.2,
    saturation: 180,
    elasticity: 0.18,
    padding: '38px',
  },
  stat: {
    overLight: true,
    cornerRadius: 26,
    displacementScale: 76,
    blurAmount: 0.18,
    saturation: 180,
    elasticity: 0.22,
    padding: '24px 18px',
  },
  actionBar: {
    overLight: true,
    cornerRadius: 28,
    displacementScale: 76,
    blurAmount: 0.18,
    saturation: 170,
    elasticity: 0.2,
    padding: '18px 22px',
  },
  button: {
    overLight: true,
    cornerRadius: 100,
    displacementScale: 62,
    blurAmount: 0.16,
    saturation: 170,
    elasticity: 0.34,
    padding: '10px 22px',
  },
  buttonSmall: {
    overLight: true,
    cornerRadius: 100,
    displacementScale: 54,
    blurAmount: 0.15,
    saturation: 165,
    elasticity: 0.32,
    padding: '8px 16px',
  },
  analysisButton: {
    overLight: true,
    cornerRadius: 100,
    displacementScale: 58,
    blurAmount: 0.16,
    saturation: 175,
    elasticity: 0.32,
    padding: '8px 18px',
  },
  playerCard: {
    overLight: true,
    cornerRadius: 30,
    displacementScale: 92,
    blurAmount: 0.18,
    saturation: 175,
    elasticity: 0.17,
    mode: 'standard',
  },
  footer: {
    overLight: true,
    cornerRadius: 0,
    displacementScale: 56,
    blurAmount: 0.14,
    saturation: 155,
    elasticity: 0.2,
    padding: '22px 24px',
  },
}
